apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-dpl
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: default
        image: mladedav/data-platform-api:{{ .Values.dockerTag }}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: configuration
          mountPath: "/config"
          readOnly: true
      volumes:
      - name: configuration
        secret:
          secretName: {{ .Chart.Name}}-config
