apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ing
  annotations:
    # kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: data.mladedav.ml
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Chart.Name }}-svc
          servicePort: 80
