apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ing
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/issuer: letsencrypt-issuer
spec:
  tls:
  - hosts:
    - {{ .Values.domain}}
    secretName: {{ .Chart.Name }}-tls
  rules:
  - host: {{ .Values.domain}}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Chart.Name }}-svc
          servicePort: 80
