apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.name }}-ing
  annotations:
    # kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  # - host:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Chart.name }}-svc
          servicePort: 80
